[package]
name = "aoc-benchmarks"
authors = ["Andreas Waidler <lintermute@mailbox.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[[bench]]
name = "puzzles"
harness = false

[dev-dependencies]
aoc = { path = "../aoc" }
criterion = "0.5.1"
paste = "1.0.15"
