[package]
name = "aoc-cli"
authors = ["Andreas Waidler <lintermute@mailbox.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
aoc = { path = "../aoc" }
tokio = { workspace = true }
